-- MySQL Script generated by MySQL Workbench
-- Tue Dec 10 09:17:36 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`company` (
  `id_company` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_business` INT(10) NULL,
  `name` VARCHAR(45) NOT NULL,
  `complete_address` VARCHAR(75) NOT NULL,
  `company_email` VARCHAR(45) NOT NULL,
  `company_phone` VARCHAR(15) NOT NULL,
  `operating_schedule` VARCHAR(150) NOT NULL,
  `end_date` DATETIME NULL,
  `company_status` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_company`),
  UNIQUE INDEX `idcompany_UNIQUE` (`id_company` ASC) VISIBLE,
  UNIQUE INDEX `company_email_UNIQUE` (`company_email` ASC) VISIBLE,
  UNIQUE INDEX `id_business_UNIQUE` (`id_business` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id_user` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `email_adress` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `birthday` DATE NOT NULL,
  `sex` ENUM('Male', 'Female') NOT NULL,
  `complete_address` VARCHAR(75) NOT NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `iduser_UNIQUE` (`id_user` ASC) VISIBLE,
  UNIQUE INDEX `email_adress_UNIQUE` (`email_adress` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`supplier_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`supplier_user` (
  `id_user` INT(10) UNSIGNED NOT NULL,
  `phone_number` VARCHAR(45) NOT NULL,
  `date_hired` DATE NOT NULL,
  `days_of_work` INT(10) UNSIGNED NOT NULL,
  `end_date` DATETIME NULL,
  PRIMARY KEY (`id_user`),
  CONSTRAINT `fk_supplier_user_user1`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`user` (`id_user`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`company_manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`company_manager` (
  `id_user` INT(10) UNSIGNED NOT NULL,
  `id_company` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id_user`),
  INDEX `fk_company_manager_company1_idx` (`id_company` ASC) VISIBLE,
  INDEX `fk_company_manager_supplier_user1_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_company_manager_company1`
    FOREIGN KEY (`id_company`)
    REFERENCES `mydb`.`company` (`id_company`),
  CONSTRAINT `fk_company_manager_supplier_user1`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`supplier_user` (`id_user`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`company_staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`company_staff` (
  `id_user` INT(10) UNSIGNED NOT NULL,
  `id_company` INT(10) UNSIGNED NOT NULL,
  `id_staff` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id_user`),
  INDEX `fk_company_staff_company1_idx` (`id_company` ASC) VISIBLE,
  INDEX `fk_company_staff_supplier_user1_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_company_staff_company1`
    FOREIGN KEY (`id_company`)
    REFERENCES `mydb`.`company` (`id_company`),
  CONSTRAINT `fk_company_staff_supplier_user1`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`supplier_user` (`id_user`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`document`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`document` (
  `id_document` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(10) UNSIGNED NOT NULL,
  `filename` VARCHAR(45) NOT NULL,
  `file_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_document`),
  INDEX `fk_document_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_document_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id_user`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`resource`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`resource` (
  `id_resource` INT(11) NOT NULL AUTO_INCREMENT,
  `rent_status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_resource`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`equipment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`equipment` (
  `resource_id` INT(11) NOT NULL,
  `options` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`resource_id`),
  INDEX `fk_Equipment_resource1_idx` (`resource_id` ASC) VISIBLE,
  CONSTRAINT `fk_Equipment_resource1`
    FOREIGN KEY (`resource_id`)
    REFERENCES `mydb`.`resource` (`id_resource`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`resident_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`resident_group` (
  `group_id` INT(11) NOT NULL AUTO_INCREMENT,
  `group_address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`group_id`),
  UNIQUE INDEX `group_address_UNIQUE` (`group_address` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`group_leader`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`group_leader` (
  `id_user` INT(10) UNSIGNED NOT NULL,
  `group_id` INT(11) NOT NULL,
  PRIMARY KEY (`id_user`),
  INDEX `fk_group_leader_resident_group1_idx` (`group_id` ASC) VISIBLE,
  CONSTRAINT `fk_group_leader_resident_group1`
    FOREIGN KEY (`group_id`)
    REFERENCES `mydb`.`resident_group` (`group_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`household`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`household` (
  `complete_address` VARCHAR(75) NOT NULL,
  PRIMARY KEY (`complete_address`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`place`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`place` (
  `resource_id` INT(11) NOT NULL,
  `maximum_capacity` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`resource_id`),
  INDEX `fk_Place_resource1_idx` (`resource_id` ASC) VISIBLE,
  CONSTRAINT `fk_Place_resource1`
    FOREIGN KEY (`resource_id`)
    REFERENCES `mydb`.`resource` (`id_resource`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`resident_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`resident_user` (
  `id_user` INT(10) UNSIGNED NOT NULL,
  `complete_address` VARCHAR(75) NOT NULL,
  `request_ability` VARCHAR(20) NOT NULL,
  `group1_id` INT(11) NULL,
  `group2_id` INT(11) NULL,
  `group3_id` INT(11) NULL DEFAULT NULL,
  `group_leader_id_user` INT(10) UNSIGNED NULL,
  `resource_id_resource` INT(11) NOT NULL,
  PRIMARY KEY (`id_user`, `resource_id_resource`),
  INDEX `fk_resident_user_user_idx` (`id_user` ASC) VISIBLE,
  INDEX `fk_resident_user_household1_idx` (`complete_address` ASC) VISIBLE,
  UNIQUE INDEX `group1_id_UNIQUE` (`group1_id` ASC) VISIBLE,
  UNIQUE INDEX `group2_id_UNIQUE` (`group2_id` ASC) VISIBLE,
  UNIQUE INDEX `group3_id_UNIQUE` (`group3_id` ASC) VISIBLE,
  INDEX `fk_resident_user_group_leader1_idx` (`group_leader_id_user` ASC) VISIBLE,
  INDEX `fk_resident_user_resource1_idx` (`resource_id_resource` ASC) VISIBLE,
  CONSTRAINT `fk_resident_user_household1`
    FOREIGN KEY (`complete_address`)
    REFERENCES `mydb`.`household` (`complete_address`),
  CONSTRAINT `fk_resident_user_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`user` (`id_user`),
  CONSTRAINT `fk_resident_user_group_leader1`
    FOREIGN KEY (`group_leader_id_user`)
    REFERENCES `mydb`.`group_leader` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_resident_user_resource1`
    FOREIGN KEY (`resource_id_resource`)
    REFERENCES `mydb`.`resource` (`id_resource`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`staff_position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`staff_position` (
  `position_title` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`position_title`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rating` (
  `id_transaction` INT NOT NULL,
  `resource_quality` INT NOT NULL,
  `money_value` INT NOT NULL,
  `timeliness` INT NOT NULL,
  `politeness` INT NOT NULL,
  `overall` INT NOT NULL,
  `resident_user_id_user` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id_transaction`),
  UNIQUE INDEX `supplier_id_UNIQUE` (`id_transaction` ASC) VISIBLE,
  INDEX `fk_rating_resident_user1_idx` (`resident_user_id_user` ASC) VISIBLE,
  CONSTRAINT `fk_rating_resident_user1`
    FOREIGN KEY (`resident_user_id_user`)
    REFERENCES `mydb`.`resident_user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`transaction` (
  `id_transaction` INT(11) NOT NULL AUTO_INCREMENT,
  `id_staff` INT(10) UNSIGNED NOT NULL,
  `id_resident` INT(10) UNSIGNED NOT NULL,
  `duration` INT(10) UNSIGNED ZEROFILL NOT NULL,
  `amount_due` DOUBLE NOT NULL,
  `status` VARCHAR(20) NOT NULL,
  `penalty_fee` DOUBLE NOT NULL,
  `payment_balance` DOUBLE NOT NULL,
  `company_staff_id_user` INT(10) UNSIGNED NOT NULL,
  `rating_id_transaction` INT NOT NULL,
  `resource_id_resource` INT(11) NOT NULL,
  PRIMARY KEY (`id_transaction`),
  INDEX `fk_transaction_resident_user1_idx` (`id_resident` ASC) VISIBLE,
  INDEX `fk_transaction_company_staff1_idx` (`company_staff_id_user` ASC) VISIBLE,
  INDEX `fk_transaction_rating1_idx` (`rating_id_transaction` ASC) VISIBLE,
  INDEX `fk_transaction_resource1_idx` (`resource_id_resource` ASC) VISIBLE,
  CONSTRAINT `fk_transaction_resident_user1`
    FOREIGN KEY (`id_resident`)
    REFERENCES `mydb`.`resident_user` (`id_user`),
  CONSTRAINT `fk_transaction_company_staff1`
    FOREIGN KEY (`company_staff_id_user`)
    REFERENCES `mydb`.`company_staff` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transaction_rating1`
    FOREIGN KEY (`rating_id_transaction`)
    REFERENCES `mydb`.`rating` (`id_transaction`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transaction_resource1`
    FOREIGN KEY (`resource_id_resource`)
    REFERENCES `mydb`.`resource` (`id_resource`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`village_staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`village_staff` (
  `id_user` INT(10) UNSIGNED NOT NULL,
  `position` VARCHAR(25) NOT NULL,
  `start_date` DATE NOT NULL,
  PRIMARY KEY (`id_user`, `position`),
  INDEX `fk_village_staff_user1_idx` (`id_user` ASC) VISIBLE,
  INDEX `fk_village_staff_system_admnistrator1_idx` (`position` ASC) VISIBLE,
  CONSTRAINT `fk_village_staff_system_admnistrator1`
    FOREIGN KEY (`position`)
    REFERENCES `mydb`.`staff_position` (`position_title`),
  CONSTRAINT `fk_village_staff_user1`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`user` (`id_user`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`registration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`registration` (
  `id_registration` INT(10) NOT NULL,
  `user_id` INT(10) UNSIGNED NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `comment` VARCHAR(200) NOT NULL,
  `user_id_user` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id_registration`),
  UNIQUE INDEX `id_registration_UNIQUE` (`id_registration` ASC) VISIBLE,
  INDEX `fk_registration_user1_idx` (`user_id_user` ASC) VISIBLE,
  CONSTRAINT `fk_registration_user1`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `mydb`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`resident_group_has_resident_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`resident_group_has_resident_user` (
  `resident_group_group_id` INT(11) NOT NULL,
  `resident_user_id_user` INT(10) UNSIGNED NOT NULL,
  `resident_user_group1_id` INT(11) NOT NULL,
  PRIMARY KEY (`resident_group_group_id`, `resident_user_id_user`, `resident_user_group1_id`),
  INDEX `fk_resident_group_has_resident_user_resident_user1_idx` (`resident_user_id_user` ASC, `resident_user_group1_id` ASC) VISIBLE,
  INDEX `fk_resident_group_has_resident_user_resident_group1_idx` (`resident_group_group_id` ASC) VISIBLE,
  CONSTRAINT `fk_resident_group_has_resident_user_resident_group1`
    FOREIGN KEY (`resident_group_group_id`)
    REFERENCES `mydb`.`resident_group` (`group_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_resident_group_has_resident_user_resident_user1`
    FOREIGN KEY (`resident_user_id_user` , `resident_user_group1_id`)
    REFERENCES `mydb`.`resident_user` (`id_user` , `group1_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`business_owner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`business_owner` (
  `id_user` INT(10) UNSIGNED NOT NULL,
  `supplier_user_id_user` INT(10) UNSIGNED NOT NULL,
  `company_id_company` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id_user`, `supplier_user_id_user`),
  INDEX `fk_business_owner_supplier_user1_idx` (`supplier_user_id_user` ASC) VISIBLE,
  INDEX `fk_business_owner_company1_idx` (`company_id_company` ASC) VISIBLE,
  CONSTRAINT `fk_business_owner_supplier_user1`
    FOREIGN KEY (`supplier_user_id_user`)
    REFERENCES `mydb`.`supplier_user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_business_owner_company1`
    FOREIGN KEY (`company_id_company`)
    REFERENCES `mydb`.`company` (`id_company`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
